AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  vpcsg:
    Type: String
Resources:
  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      Engine: 'mysql'
      EngineVersion: '5.7'
      DBInstanceClass: 'db.t2.micro'
      DBInstanceIdentifier: 'MyDBInstance'
      MasterUsername: 'admin'
      MasterUserPassword: 'MyPassword123'
      VPCSecurityGroups:
        - !Ref vpcsg
      PubliclyAccessible: true